
title: "" # the name of your site, e.g. ACME Corp.

baseurl: /jekyll-bulma-iek-dypa-komotinis
url: http://F20F20.github.io


plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  
  
  
paginate: 5
paginate_path: "news/page:num/"
